# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: MeshAgent.EnterpriseCodex
PackageVersion: 0.53.1-meshagent.0.153.4
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: codex.exe
  PortableCommandAlias: codex
UpgradeBehavior: uninstallPrevious
Commands:
- codex
Installers:
- Architecture: x64
  InstallerUrl: https://storage.googleapis.com/meshagent-enterprise-codex-builds/0.53.1/enterprise-codex-0.53.1-meshagent.0.153.4-windows-x86_64.zip
  InstallerSha256: E888298C0A329D6E4E2D4747F507DD3FF4B058A213A190C13CE618996A1CB013
- Architecture: arm64
  InstallerUrl: https://storage.googleapis.com/meshagent-enterprise-codex-builds/0.53.1/enterprise-codex-0.53.1-meshagent.0.153.4-windows-arm64.zip
  InstallerSha256: F7DA81096C58D6F34D9E46CE6A4341B4976A10384DAAE46DD2639F07D86C64AD
ManifestType: installer
ManifestVersion: 1.10.0
