# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: MeshAgent.EnterpriseCodex
PackageVersion: 0.53.4-meshagent.0.160.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: codex.exe
  PortableCommandAlias: codex
UpgradeBehavior: uninstallPrevious
Commands:
- codex
Installers:
- Architecture: x64
  InstallerUrl: https://storage.googleapis.com/meshagent-enterprise-codex-builds/0.53.4/enterprise-codex-0.53.4-meshagent.0.160.0-windows-x86_64.zip
  InstallerSha256: 7B1A8E37CF9F906FFB89BCA05E09058A45031DB86234CD07F00E272F39A94AFD
- Architecture: arm64
  InstallerUrl: https://storage.googleapis.com/meshagent-enterprise-codex-builds/0.53.4/enterprise-codex-0.53.4-meshagent.0.160.0-windows-arm64.zip
  InstallerSha256: 9A4A615162DFD41635C8359C3F23512E4C2522FD2F4913FEC71FF7AA90CFD9D2
ManifestType: installer
ManifestVersion: 1.10.0
