# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: MeshAgent.EnterpriseCodex
PackageVersion: 0.53.0-meshagent.0.153.4
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: codex.exe
  PortableCommandAlias: codex
UpgradeBehavior: uninstallPrevious
Commands:
- codex
Installers:
- Architecture: x64
  InstallerUrl: https://storage.googleapis.com/meshagent-enterprise-codex-builds/0.53.0/enterprise-codex-0.53.0-meshagent.0.153.4-windows-x86_64.zip
  InstallerSha256: 415D1968420F74B2461425078E63946B4BCBFA0F0937BC51699744DBA452BDEB
- Architecture: arm64
  InstallerUrl: https://storage.googleapis.com/meshagent-enterprise-codex-builds/0.53.0/enterprise-codex-0.53.0-meshagent.0.153.4-windows-arm64.zip
  InstallerSha256: 6858D25276561C30A893B7EEC4BEA6332BC2F7CF5A2203094035F1761BE4D7E0
ManifestType: installer
ManifestVersion: 1.10.0
