# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: MeshAgent.EnterpriseCodex
PackageVersion: 0.53.2-meshagent.0.153.4
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: codex.exe
  PortableCommandAlias: codex
UpgradeBehavior: uninstallPrevious
Commands:
- codex
Installers:
- Architecture: x64
  InstallerUrl: https://storage.googleapis.com/meshagent-enterprise-codex-builds/0.53.2/enterprise-codex-0.53.2-meshagent.0.153.4-windows-x86_64.zip
  InstallerSha256: 3978372F4E125D680668CE05EBD52B72FCF1A10F6F3C227C9C5E38D2CB15AA34
- Architecture: arm64
  InstallerUrl: https://storage.googleapis.com/meshagent-enterprise-codex-builds/0.53.2/enterprise-codex-0.53.2-meshagent.0.153.4-windows-arm64.zip
  InstallerSha256: 7D644985614861D3A33E33EFCA0386BE80F14DCB3EBFD24EAC7A30A90E799E82
ManifestType: installer
ManifestVersion: 1.10.0
